Try and work out where the az cli is located

diff --git a/apps/db-operations-service/Dockerfile-azure b/apps/db-operations-service/Dockerfile-azure
--- a/apps/db-operations-service/Dockerfile-azure
+++ b/apps/db-operations-service/Dockerfile-azure
@@ -20,7 +20,12 @@ RUN chmod +x /app/scripts/*.sh
 ENV PATH="${PATH}:/app/scripts"
 
 # Update PATH to include the location of 'az'
-ENV PATH="${PATH}:/usr/local/bin"
+RUN AZ_PATH=$(find / -type f -name az | head -n 1) && \
+    if [ -n "$AZ_PATH" ]; then \
+    ln -s $AZ_PATH /usr/local/bin/az; \
+    else \
+    echo "Azure CLI executable not found." && exit 1; \
+    fi
 
 ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
     AzureFunctionsJobHost__Logging__Console__IsEnabled=true \
