SWIP-582 Integrate Moodle OIDC plugin with build and deploy workflows
Added integration for OIDC plugin to build / deploy
Also added wiring for web service setup in build
Made Terraform state management more reliable in case of intermittent Azure errors
Added more auth related endpoints with correct front-door URLs

diff --git a/apps/moodle-apps-azure/justfile b/apps/moodle-apps-azure/justfile
--- a/apps/moodle-apps-azure/justfile
+++ b/apps/moodle-apps-azure/justfile
@@ -19,10 +19,16 @@ restore:
   #!/bin/bash
   # The Moodle image build process requires these additional files to be sourced from the repo
   PHP_CONFIG_FILE="../moodle-docker/config.php"
+  WEB_SERVICE_SETUP_FILE="../../scripts/setup_moodle_webservice.php"
   MOODLE_SCRIPTS_DIR="../moodle-ddev/.ddev/commands/web"
   DESTINATION_DIR="./"
 
   errors=0
+
+  if [ ! -f "$WEB_SERVICE_SETUP_FILE" ]; then
+    echo "Error: required file '$WEB_SERVICE_SETUP_FILE' not found." >&2
+    errors=1
+  fi
 
   if [ ! -f "$PHP_CONFIG_FILE" ]; then
     echo "Error: required file '$PHP_CONFIG_FILE' not found." >&2
@@ -45,6 +51,7 @@ restore:
 
   echo "Copying additional files for Docker Moodle image build..."
   cp "$PHP_CONFIG_FILE" "$DESTINATION_DIR"
+  cp "$WEB_SERVICE_SETUP_FILE" "$DESTINATION_DIR"
   cp "$MOODLE_SCRIPTS_DIR"/* "$DESTINATION_DIR"
 
 build:
@@ -105,8 +112,9 @@ database-updates resource-group web-app-name full-image-tag:
 
   sudo apt-get update && sudo apt-get install -y sshpass
 
-  # The SSH sesion doesn't inherit all of the variables from the app service / startup script
-  # so we have to pass them all manually / recreate them
+  # The SSH sesion doesn't inherit all of the variables from the app service / startup 
+  # We pass any sensitive variables explicitly - these will have been fetched from the
+  # web app settings.
   sshpass -p "$AZURE_KUDU_SSH_PASSWORD" ssh \
   -T \
   -o TCPKeepAlive=no \
@@ -121,12 +129,15 @@ database-updates resource-group web-app-name full-image-tag:
   $AZURE_KUDU_SSH_USER@127.0.0.1 <<EOF
   export MOODLE_ADMIN_PASSWORD="$MOODLE_ADMIN_PASSWORD"
   export POSTGRES_PASSWORD="$POSTGRES_PASSWORD"
+  export MOODLE_WEB_SERVICE_USER_PASSWORD="$MOODLE_WEB_SERVICE_USER_PASSWORD"
+  export AUTH_SERVICE_CLIENT_SECRET="$AUTH_SERVICE_CLIENT_SECRET"
   set -euo pipefail
 
   echo "Starting Moodle database install / update"
 
   cd /app
-  # load all the variables into THIS shell
+  # Load all the variables into THIS shell - all of the non-sensitive env variables were
+  # saved during container startup, so we could reuse them here.
   source ./restore-env.sh /app/env.txt
 
   # run the maintenance script (it must terminate)
