SWIP-464 Terraform refactor (iteration 3!) (#31)
Also includes SWIP-381, Terraform bootstrap: was easier to include with the overall refactor
Naming conventions
Pinning of provider versions
Separation of infrastructure concerns
Elimination of warnings during plan or apply (one remaining, but much cleaner)
Ignoring attributes such as tags when planning changes
Move non-sensitive environment variables from Github Actions to Git / Terraform code (better auditability)
Use Terraform tfvars as the main source of truth (a new Github Action can read these and make them available to the workflow)
Github secrets - should only contain the Azure subscription related credentials, such as AZ_CLIENT_ID etc. There are some passwords remaining, but these will be reviewed
Github environment variables - should only contains user names / emails.

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -47,15 +47,14 @@ jobs:
       tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
 
     steps:
-      # Checkout the repository to the GitHub Actions runner
       - name: Checkout
         uses: actions/checkout@v4
 
-      # Install the latest version of the Terraform CLI
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
         with:
-          terraform_version: 1.10.5
+          # Terraform is pinned to the version below - this should be reviewed regularly
+          terraform_version: 1.11.3
           terraform_wrapper: false
 
       # Checks that all Terraform configuration files adhere to a canonical format
@@ -71,34 +70,68 @@ jobs:
           tenant-id: ${{ secrets.AZ_TENANT_ID }}
           subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
 
-      # Initialise a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+      # Generates Terraform input variables by merging the global and environment variables
+      # Supports substitution of global variable values in environment specific variables
+      - name: Load Terraform Variables
+        uses: ./.github/actions/pre-process-terraform-variables
+        with:
+          environment: ${{ inputs.environment }}
+          add_as_env_vars: true
+
+      - name: Generate Terraform State Variables
+        shell: bash
+        run: |
+          export TF_VAR_FILE=/tmp/merged.tfvars
+          export RESOURCE_NAME_PREFIX=$(awk -F'"' '/resource_name_prefix/ {print $2}' $TF_VAR_FILE)
+          echo "TF_STATE_AZURE_REGION=$(awk -F'\"' '/azure_region/ {print $2}' $TF_VAR_FILE)" >> $GITHUB_ENV
+          echo "TF_STATE_RESOURCE_GROUP=$RESOURCE_NAME_PREFIX-swip-rg-tfstate" >> $GITHUB_ENV
+          echo "TF_STATE_STORAGE_ACCOUNT_NAME=${RESOURCE_NAME_PREFIX}swipsatfstate" >> $GITHUB_ENV
+          echo "TF_STATE_CONTAINER_NAME=${RESOURCE_NAME_PREFIX}swipconttfstate" >> $GITHUB_ENV
+          echo "TF_STATE_KEY=$RESOURCE_NAME_PREFIX-swip-tfstate" >> $GITHUB_ENV
+          echo "TF_VAR_FILE=$TF_VAR_FILE" >> $GITHUB_ENV
+
+      # Idempotent step - create Terraform state resources if they don't exist
+      # CIP policy requires use of standard tags for resources
+      - name: Ensure Terraform State Resources Exist
+        run: |
+          export ENVIRONMENT_TAG=$(awk -F'"' '/environment_tag/ {print $2}' $TF_VAR_FILE)
+          export PARENT_BUSINESS_TAG=$(awk -F'"' '/parent_business_tag/ {print $2}' $TF_VAR_FILE)
+          export PRODUCT_TAG=$(awk -F'"' '/product_tag/ {print $2}' $TF_VAR_FILE)
+          export SERVICE_OFFERING_TAG=$(awk -F'"' '/service_offering_tag/ {print $2}' $TF_VAR_FILE)
+          export TAGS=(
+            "Environment=$ENVIRONMENT_TAG"
+            "Parent Business=$PARENT_BUSINESS_TAG"
+            "Product=$PRODUCT_TAG"
+            "Service Offering=$SERVICE_OFFERING_TAG"
+          )
+          chmod +x ./scripts/init-tf-state.sh
+          ./scripts/init-tf-state.sh $TF_STATE_AZURE_REGION $TF_STATE_RESOURCE_GROUP $TF_STATE_STORAGE_ACCOUNT_NAME $TF_STATE_CONTAINER_NAME $TF_STATE_KEY "${TAGS[@]}"
+
       - name: Terraform Init
         run: >
           terraform init
-          -backend-config="resource_group_name=${{ secrets.TERRAFORM_STATE_RESOURCE_GROUP }}"
-          -backend-config="storage_account_name=${{ secrets.TERRAFORM_STATE_STORAGE_ACCOUNT_NAME }}"
-          -backend-config="container_name=${{ secrets.TERRAFORM_STATE_STORAGE_CONTAINER_NAME }}"
-          -backend-config="key=${{ secrets.TERRAFORM_STATE_KEY }}"
+          -backend-config="resource_group_name=$TF_STATE_RESOURCE_GROUP"
+          -backend-config="storage_account_name=$TF_STATE_STORAGE_ACCOUNT_NAME"
+          -backend-config="container_name=$TF_STATE_CONTAINER_NAME"
+          -backend-config="key=$TF_STATE_KEY"
 
-      # Generates Terraform input variables
-      - name: Generate Terraform Variables
-        shell: bash
-        env:
-          WEB_SECRETS: ${{ toJSON(secrets) }}
-          WEB_VARS: ${{ toJSON(vars) }}
-        run: |
-          printf '%s\n' "$WEB_SECRETS" > tmp-secrets.json
-          printf '%s\n' "$WEB_VARS" > tmp-vars.json
-          jq 'with_entries(.key |= ascii_downcase)' tmp-secrets.json > web-secrets.auto.tfvars.json
-          jq 'with_entries(.key |= ascii_downcase)' tmp-vars.json > web-vars.auto.tfvars.json
-
-      # Generates an execution plan for Terraform
-      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+      # Generates an execution plan for Terraform, exit codes:
+      # - 0 indicated no changes
+      # - 1 a terraform failure
+      # - 2 there are pending changes.
       - name: Terraform Plan
         id: tf-plan
         run: |
+          # Only import the variables we need
           export exitcode=0
-          terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+          terraform plan -detailed-exitcode -no-color -out tfplan \
+            -var-file=$TF_VAR_FILE \
+            -var='moodle_admin_password=${{ secrets.MOODLE_ADMIN_PASSWORD }}' \
+            -var='trace_webapp_admin_password=${{ secrets.TRACE_WEBAPP_ADMIN_PASSWORD }}' \
+            -var='moodle_admin_email=${{ secrets.MOODLE_ADMIN_EMAIL }}' \
+            -var='moodle_admin_user=${{ secrets.MOODLE_ADMIN_USER }}' \
+            -var='trace_webapp_admin_user=${{ secrets.TRACE_WEBAPP_ADMIN_USER }}' \
+            || export exitcode=$?
 
           echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
 
@@ -109,7 +142,6 @@ jobs:
             exit 0
           fi
 
-      # Terraform Apply
       - name: Terraform Apply
         if: ${{ inputs.action == 'Plan & Apply' }}
         env:
